In [106]:
import pandas as pd

In [107]:
# df0 = pd.read_csv("data.csv")
# df1 = pd.read_csv("data1.csv")
# df2 = pd.read_csv("data2.csv")
# df3 = pd.read_csv("data3.csv")
# df4 = pd.read_csv("data4.csv")
# df5 = pd.read_csv("data5.csv")
# df6 = pd.read_csv("data6.csv")

In [108]:
# df0 = pd.read_csv("data0.csv")
# df2 = pd.read_csv("data2.csv")
# df4 = pd.read_csv("data4.csv")

In [109]:
df1 = pd.read_csv("data2/gamingchair1.csv")
df2 = pd.read_csv("data2/gamingchair2.csv")
df3 = pd.read_csv("data2/gamingchair3.csv")
df4 = pd.read_csv("data2/gamingchair4.csv")
df5 = pd.read_csv("data2/gamingchair5.csv")
df6 = pd.read_csv("data2/gamingchair6.csv")
df7 = pd.read_csv("data2/gamingchair7.csv")

In [110]:
# df = pd.concat([df1, df2, df3,df4,df5,df6,df7 ])

In [111]:
# df = df.reset_index()

In [112]:
# df

In [113]:
# df = df[["url", "content","useful"]]
# df = df[["url", "content"]]

In [114]:
# df = df.drop_duplicates()

In [115]:
# df

In [116]:
# df['content'] = df['content'].str.split('.')
# df = df.explode('content')

In [117]:

# df1['content'] = df1['content'].str.split('.')
# df1 = df1.explode('content')
# df2['content'] = df2['content'].str.split('.')
# df2 = df2.explode('content')
# df3['content'] = df3['content'].str.split('.')
# df3 = df3.explode('content')
# df4['content'] = df4['content'].str.split('.')
# df4 = df4.explode('content')

In [118]:
#  = pd.read_csv("gamingchair5.csv")
#  = pd.read_csv("gamingchair6.csv")
#  = pd.read_csv("gamingchair7.csv")
# df5['content'] = df5['content'].str.split('.')
# df5 = df5.explode('content')
# df6['content'] = df6['content'].str.split('.')
# df6 = df6.explode('content')

# df7['content'] = df7['content'].str.split('.')
# df7 = df7.explode('content')

In [119]:
df7= df7.loc[df7["content"].str.len()>= 2]

In [120]:
# df = df.reset_index(drop=True)

In [121]:

import google.generativeai as genai
import os
import time

In [122]:
# import pprint
# for model in genai.list_models():
#     pprint.pprint(model)

In [123]:


from dotenv import load_dotenv
client =  genai.configure(api_key=os.getenv("GOOGLE_GEMINI_API_KEY"))
def gemini_usefulness(column):
    new_list = []
    batch_size = 5  # Process 5 rows at a time
    for i in range(0, len(column), batch_size):
        batch = column[i:i + batch_size]
        print(i)
        for mehmeh in batch:
            try:
                model = genai.GenerativeModel('gemini-2.0-flash-lite')
                response = model.generate_content([
                    f"For the string provided, please respond with '1' if the data is relevant to give a gaming chair product design review and improvements and modifications, and '0' if it is not, nothing else : {mehmeh}"
                ])
                new_list.append(response.text)
            except Exception as e:
                print(f"An error occurred processing: {mehmeh}. Error: {e}")
                new_list.append(None) #Append None or some other error indicator
        if i + batch_size < len(column): # only sleep if there are more rows to process.
            print("Sleeping for half minute...")
            time.sleep(30)  # Sleep for 60 seconds (1 minute)
    return new_list

In [124]:
def gemini_sentiment(column):
    new_list = []
    batch_size = 5  # Process 5 rows at a time
    for i in range(0, len(column), batch_size):
        batch = column[i:i + batch_size]
        print(i)
        for mehmeh in batch:
            try:
                model = genai.GenerativeModel('gemini-2.0-flash-lite')
                response = model.generate_content([
                    f"Analyze the sentiment of the following text and return either positive, negative, or neutral: {mehmeh}"
                ])
                new_list.append(response.text)
            except Exception as e:
                print(f"An error occurred processing: {mehmeh}. Error: {e}")
                new_list.append(None) #Append None or some other error indicator
        if i + batch_size < len(column): # only sleep if there are more rows to process.
            print("Sleeping for 30 seconds...")
            time.sleep(30)  # Sleep for 60 seconds (1 minute)
    return new_list

In [125]:
import json

def process_review_batch(column):
    new_list = []
    batch_size = 5  # Process 5 rows at a time
    for i in range(0, len(column), batch_size):
        batch = column[i:i + batch_size]
        print(i)
        for mehmeh in batch:
            try:
                model = genai.GenerativeModel('gemini-2.0-flash')
                response = model.generate_content([
                    f"""
    Analyze the following product review and perform these tasks:

    1.  Extract any pros and cons. If the review contains both pros and cons, separate them. If the review only contains pros or cons, or neither, indicate that.
    2.  Analyze the sentiment of each pro and con (if present) and classify it as 'positive', 'negative', or 'neutral'.
    3.  Determine if the review is useful for training a model to understand product reviews. A review is useful if it provides specific details about the product's features, performance, or user experience.
    4.  Return the results in a semicolon-separated string format with the following order:
        * Pros (a comma-separated string of pros, or null if none).
        * Cons (a comma-separated string of cons, or null if none).
        * Useful for training (1 if useful, 0 if not).
        * Overall sentiment (positive, negative, or neutral).

    Review: {mehmeh}
"""
                ])
                new_list.append(response.text)
            except Exception as e:
                print(f"An error occurred processing: {mehmeh}. Error: {e}")
                new_list.append(None) #Append None or some other error indicator
        if i + batch_size < len(column): # only sleep if there are more rows to process.
            print("Sleeping for half minute...")
            time.sleep(30)  # Sleep for 60 seconds (1 minute)
    return new_list

In [126]:

# batch_size = 5  # Adjust batch size as needed
# all_results = []

# for i in range(0, len(df1), batch_size):
#     batch = df1['content'][i:i + batch_size].tolist()
#     batch_results = process_review_batch(batch)
#     all_results.extend(batch_results)
#     if i + batch_size < len(df1):
#         print("Sleeping for 30 seconds...")
#         time.sleep(30) # sleep between batches.

# processed_df = pd.DataFrame(all_results)
# final_df = pd.concat([df1, processed_df], axis=1)

# print(final_df)
# final_df.to_csv('processed_reviews_batched1.csv')

0

In [ ]:
mehmehlist1 = process_review_batch(df1["content"])
df1["result"] = mehmehlist1
df1.to_csv("data/processresult1_1.csv",index=False)

In [137]:
mehmehlist2 = process_review_batch(df2["content"])
df2["result"] = mehmehlist2
df2.to_csv("data/processresult2.csv",index=False)

0
Sleeping for half minute...
5
Sleeping for half minute...
10
Sleeping for half minute...
15
Sleeping for half minute...
20
Sleeping for half minute...
25
Sleeping for half minute...
30

In [139]:
mehmehlist3 = process_review_batch(df3["content"])
df3["result"] = mehmehlist3
df3.to_csv("data/processresult3.csv",index=False)

0
Sleeping for half minute...
5
Sleeping for half minute...
10
Sleeping for half minute...
15
Sleeping for half minute...
20
Sleeping for half minute...
25
Sleeping for half minute...
30
Sleeping for half minute...
35
Sleeping for half minute...
40
Sleeping for half minute...
45
Sleeping for half minute...
50
Sleeping for half minute...
55
Sleeping for half minute...
60
Sleeping for half minute...
65

In [140]:
mehmehlist4 = process_review_batch(df4["content"])
df4["result"] = mehmehlist4
df4.to_csv("data/processresult4.csv",index=False)

0
Sleeping for half minute...
5

In [141]:
mehmehlist5 = process_review_batch(df5["content"])
df5["result"] = mehmehlist5
df5.to_csv("data/processresult5.csv",index=False)

0
Sleeping for half minute...
5
Sleeping for half minute...
10
Sleeping for half minute...
15
Sleeping for half minute...
20
Sleeping for half minute...
25
Sleeping for half minute...
30
Sleeping for half minute...
35
Sleeping for half minute...
40
Sleeping for half minute...
45
Sleeping for half minute...
50
Sleeping for half minute...
55
Sleeping for half minute...
60
Sleeping for half minute...
65
Sleeping for half minute...
70
Sleeping for half minute...
75
Sleeping for half minute...
80
Sleeping for half minute...
85
Sleeping for half minute...
90
Sleeping for half minute...
95

In [142]:
mehmehlist6 = process_review_batch(df6["content"])
df6["result"] = mehmehlist6
df6.to_csv("data/processresult6.csv",index=False)

0
Sleeping for half minute...
5
Sleeping for half minute...
10
Sleeping for half minute...
15
Sleeping for half minute...
20
Sleeping for half minute...
25
Sleeping for half minute...
30
Sleeping for half minute...
35
Sleeping for half minute...
40
Sleeping for half minute...
45
Sleeping for half minute...
50
Sleeping for half minute...
55
Sleeping for half minute...
60
Sleeping for half minute...
65
Sleeping for half minute...
70
Sleeping for half minute...
75
Sleeping for half minute...
80
Sleeping for half minute...
85
Sleeping for half minute...
90
Sleeping for half minute...
95

In [ ]:
mehmehlist2 = process_review_batch(df2["content"])
df2["result"] = mehmehlist2
df2.to_csv("data/processresult2.csv",index=False)

In [134]:

mehmeh = df1["result"][0]

In [136]:
mehmeh.split(';')

["Here's the analysis of the product review in the requested format:\n\n**1. Extract Pros and Cons:**\n\n**Pros:**\n* Superior materials that won’t break down\n* Lots of styles and colors to choose from\n* Scientifically designed for lasting durability\n* Super comfortable\n* Looks professional enough for an office\n* Backed by up to a five-year warranty\n* Incredible selection of accessories\n* Alternative armrests with memory foam can be magnetically swapped out with the default ones\n* Headrests (which also magnetically attach) and lumbar support pillows are made with Secretlab’s special cold-cured foam, ready to add comfort\n\n**Cons:**\n* Somewhat expensive\n* No mesh options\n* Realistically only one chair shape\n* Older chair models challenging to find in stock\n* Napa leather upholstery is known to peel and crack (currently being phased out)\n* Reduction of options makes them less of a shoo-in for the absolute best gaming chair\n\n**2. Sentiment Analysis:**\n\n*   **Pros:** All pros express positive sentiment.\n*   **Cons:** All cons express negative sentiment.\n\n**3. Usefulness for Training:**\n\nThe review is useful for training a model because it provides specific details about the product's materials, design, comfort, style options, durability, accessories, and warranty. It also details the downsides like price, limited mesh options, and potential issues with the upholstery.\n\n**4. Results in the specified format:**\n\nSuperior materials that won’t break down,Lots of styles and colors to choose from,Scientifically designed for lasting durability,Super comfortable,Looks professional enough for an office,Backed by up to a five-year warranty,Incredible selection of accessories,Alternative armrests with memory foam can be magnetically swapped out with the default ones,Headrests (which also magnetically attach) and lumbar support pillows are made with Secretlab’s special cold-cured foam, ready to add comfort",
 'Somewhat expensive,No mesh options,Realistically only one chair shape,Older chair models challenging to find in stock,Napa leather upholstery is known to peel and crack (currently being phased out),Reduction of options makes them less of a shoo-in for the absolute best gaming chair',
 '1',
 'positive\n']

In [130]:
# mehmehlist7 = gemini_sentiment(df7["content"])
# df7["sentiment"] = mehmehlist7
# df7.to_csv("data/gamingsentiment7.csv",index=False)

In [131]:
print(xxxxxxxxxxxxxxxxx)

NameError: name 'xxxxxxxxxxxxxxxxx' is not defined

In [ ]:
# mehmehlist4 = gemini_usefulness(df["content"])

In [ ]:
# mehmehlist1 = gemini_usefulness(df1["content"])
# df1["usefulness2"] = mehmehlist1
# df1.to_csv("gamingchairdatacleaned1.csv",index=False)
# mehmehlist2 = gemini_usefulness(df2["content"])
# df2["usefulness2"] = mehmehlist2
# df2.to_csv("gamingchairdatacleaned2.csv",index=False)

# mehmehlist3 = gemini_usefulness(df3["content"])
# df3["usefulness2"] = mehmehlist3
# df3.to_csv("gamingchairdatacleaned3.csv",index=False)
# mehmehlist4 = gemini_usefulness(df4["content"])
# df4["usefulness2"] = mehmehlist4
# df4.to_csv("data/gamingchairdatacleaned4.csv",index=False)
# mehmehlist5 = gemini_usefulness(df5["content"])
# df5["usefulness2"] = mehmehlist5
# df5.to_csv("gamingchairdatacleaned5.csv",index=False)
# mehmehlist6 = gemini_usefulness(df6["content"])
# df6["usefulness2"] = mehmehlist6
# df6.to_csv("gamingchairdatacleaned6.csv",index=False)

In [ ]:
mehmehlist7 = gemini_usefulness(df7["content"])
df7["usefulness2"] = mehmehlist7
df7.to_csv("gamingchairdatacleaned7.csv",index=False)

0
Sleeping for half minute...
5
Sleeping for half minute...
10
Sleeping for half minute...
15
Sleeping for half minute...
20
Sleeping for half minute...
25
Sleeping for half minute...
30
Sleeping for half minute...
35
Sleeping for half minute...
40
Sleeping for half minute...
45
Sleeping for half minute...
50
Sleeping for half minute...
55
Sleeping for half minute...
60
Sleeping for half minute...
65
Sleeping for half minute...
70
Sleeping for half minute...
75
Sleeping for half minute...
80
Sleeping for half minute...
85
Sleeping for half minute...
90
Sleeping for half minute...
95

In [ ]:
mehmehlist1 = gemini_sentiment(df1["content"])
df1["sentiment"] = mehmehlist1
df1.to_csv("data/gamingsentiment1.csv",index=False)

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30
Sleeping for 30 seconds...
35
Sleeping for 30 seconds...
40

In [ ]:
mehmehlist2 = gemini_sentiment(df2["content"])
df2["sentiment"] = mehmehlist2
df2.to_csv("data/gamingsentiment2.csv",index=False)

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30
Sleeping for 30 seconds...
35
Sleeping for 30 seconds...
40
Sleeping for 30 seconds...
45
Sleeping for 30 seconds...
50
Sleeping for 30 seconds...
55
Sleeping for 30 seconds...
60
Sleeping for 30 seconds...
65
Sleeping for 30 seconds...
70
Sleeping for 30 seconds...
75
Sleeping for 30 seconds...
80
Sleeping for 30 seconds...
85
Sleeping for 30 seconds...
90
Sleeping for 30 seconds...
95
Sleeping for 30 seconds...
100
Sleeping for 30 seconds...
105
Sleeping for 30 seconds...
110
Sleeping for 30 seconds...
115
Sleeping for 30 seconds...
120
Sleeping for 30 seconds...
125
Sleeping for 30 seconds...
130
Sleeping for 30 seconds...
135

In [ ]:
mehmehlist3 = gemini_sentiment(df3["content"])
df3["sentiment"] = mehmehlist3
df3.to_csv("data/gamingsentiment3.csv",index=False)

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30
Sleeping for 30 seconds...
35
Sleeping for 30 seconds...
40
Sleeping for 30 seconds...
45
Sleeping for 30 seconds...
50
Sleeping for 30 seconds...
55
Sleeping for 30 seconds...
60
Sleeping for 30 seconds...
65
Sleeping for 30 seconds...
70
Sleeping for 30 seconds...
75
Sleeping for 30 seconds...
80
Sleeping for 30 seconds...
85
Sleeping for 30 seconds...
90
Sleeping for 30 seconds...
95
Sleeping for 30 seconds...
100
Sleeping for 30 seconds...
105
Sleeping for 30 seconds...
110
Sleeping for 30 seconds...
115
Sleeping for 30 seconds...
120
Sleeping for 30 seconds...
125
Sleeping for 30 seconds...
130
Sleeping for 30 seconds...
135
Sleeping for 30 seconds...
140
Sleeping for 30 seconds...
145
Sleeping for 30 seconds...
150
Sleeping for 30 seconds...
155
Sleeping for 30 seconds...
160
Sleeping for 30 seconds...
165
Sleeping for 30 seconds...
170
Sleeping for 30 seconds...
175

In [ ]:
def gemini_sentiment2(column):
    new_list = []
    batch_size = 5  # Process 5 rows at a time
    for i in range(0, len(column), batch_size):
        batch = column[i:i + batch_size]
        print(i)
        for mehmeh in batch:
            try:
                model = genai.GenerativeModel('gemini-2.0-pro-exp')
                response = model.generate_content([
                    f"Analyze the sentiment of the following text and return either positive, negative, or neutral: {mehmeh}"
                ])
                new_list.append(response.text)
            except Exception as e:
                print(f"An error occurred processing: {mehmeh}. Error: {e}")
                new_list.append(None) #Append None or some other error indicator
        if i + batch_size < len(column): # only sleep if there are more rows to process.
            print("Sleeping for 30 seconds...")
            time.sleep(30)  # Sleep for 60 seconds (1 minute)
    return new_list

In [ ]:
mehmehlist4 = gemini_sentiment(df4["content"])
df4["sentiment"] = mehmehlist4
df4.to_csv("data/gamingsentiment4.csv",index=False)

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30

In [ ]:
mehmehlist5 = gemini_sentiment(df5["content"])
df5["sentiment"] = mehmehlist5
df5.to_csv("data/gamingsentiment5.csv",index=False)

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30
Sleeping for 30 seconds...
35
Sleeping for 30 seconds...
40
Sleeping for 30 seconds...
45
Sleeping for 30 seconds...
50
Sleeping for 30 seconds...

KeyboardInterrupt:

In [ ]:
mehmehlist7 = gemini_sentiment(df7["content"])
df7["usefulness2"] = mehmehlist7
df7.to_csv("gamingchairdatacleaned7.csv",index=False)

In [ ]:
print(xxxxxxxxxxxxx)

In [ ]:
dfmehmeh = pd.read_csv("datacleaned.csv")
dfmehmeh

,url,content,useful,usefulness2
0,https://www.t3.com/reviews/secretlab-titan-evo...,The Secretlab Titan Evo Lite is a brand-new ch...,1,1\n
1,https://www.t3.com/reviews/secretlab-titan-evo...,"It is designed to offer ""95% of the premium e...",1,1\n
2,https://gamerant.com/secretlab-titan-evo-lite-...,"As Secretlab explains, the chair features 95% ...",1,1\n
3,https://gamerant.com/secretlab-titan-evo-lite-...,"And in our testing, the TITAN Evo Lite doesn'...",1,1\n
4,https://www.gamespot.com/articles/secretlabs-n...,"Overall, Secretlab's Titan Evo Lite is a fanta...",1,1\n
...,...,...,...,...
808,https://www.pcgamer.com/hardware/shhh-dont-tel...,Secretlab Titan Evo Lite | Leatherette or sof...,1,1\n
809,https://www.pcgamer.com/hardware/shhh-dont-tel...,Secretlab Titan Evo Lite | Leatherette or sof...,1,1\n
810,https://www.amazon.com/Secretlab-Titan-Black-L...,Secretlab Titan Evo Lite in Black Prime 2,1,1\n
811,https://www.amazon.com/Secretlab-Titan-Black-L...,0 Leatherette Gaming Chair - Reclining - Ergon...,1,1\n
812,https://www.amazon.com/Secretlab-Titan-Black-L...,Secretlab Titan Evo Black Gaming Chair - Recl...,1,1\n

In [ ]:
dfmehmeh2 = dfmehmeh[dfmehmeh["usefulness2"]=="1\n"]
dfmehmeh2

,url,content,useful,usefulness2
0,https://www.t3.com/reviews/secretlab-titan-evo...,The Secretlab Titan Evo Lite is a brand-new ch...,1,1\n
1,https://www.t3.com/reviews/secretlab-titan-evo...,"It is designed to offer ""95% of the premium e...",1,1\n
2,https://gamerant.com/secretlab-titan-evo-lite-...,"As Secretlab explains, the chair features 95% ...",1,1\n
3,https://gamerant.com/secretlab-titan-evo-lite-...,"And in our testing, the TITAN Evo Lite doesn'...",1,1\n
4,https://www.gamespot.com/articles/secretlabs-n...,"Overall, Secretlab's Titan Evo Lite is a fanta...",1,1\n
...,...,...,...,...
808,https://www.pcgamer.com/hardware/shhh-dont-tel...,Secretlab Titan Evo Lite | Leatherette or sof...,1,1\n
809,https://www.pcgamer.com/hardware/shhh-dont-tel...,Secretlab Titan Evo Lite | Leatherette or sof...,1,1\n
810,https://www.amazon.com/Secretlab-Titan-Black-L...,Secretlab Titan Evo Lite in Black Prime 2,1,1\n
811,https://www.amazon.com/Secretlab-Titan-Black-L...,0 Leatherette Gaming Chair - Reclining - Ergon...,1,1\n
812,https://www.amazon.com/Secretlab-Titan-Black-L...,Secretlab Titan Evo Black Gaming Chair - Recl...,1,1\n

In [ ]:
dfmehmeh2.to_csv("datacleaned2.csv",index=False)

In [ ]:
mehmehlist5 = gemini_sentiment(dfmehmeh2["content"])

0
Sleeping for 30 seconds...
5
Sleeping for 30 seconds...
10
Sleeping for 30 seconds...
15
Sleeping for 30 seconds...
20
Sleeping for 30 seconds...
25
Sleeping for 30 seconds...
30
Sleeping for 30 seconds...
35
Sleeping for 30 seconds...
40
Sleeping for 30 seconds...
45
Sleeping for 30 seconds...
50
Sleeping for 30 seconds...
55
Sleeping for 30 seconds...
60
Sleeping for 30 seconds...
65
Sleeping for 30 seconds...
70
Sleeping for 30 seconds...
75
Sleeping for 30 seconds...
80
Sleeping for 30 seconds...
85
Sleeping for 30 seconds...
90
Sleeping for 30 seconds...
95
Sleeping for 30 seconds...
100
Sleeping for 30 seconds...
105
Sleeping for 30 seconds...
110
Sleeping for 30 seconds...
115
Sleeping for 30 seconds...
120
Sleeping for 30 seconds...
125
Sleeping for 30 seconds...
130
Sleeping for 30 seconds...
135
Sleeping for 30 seconds...
140
Sleeping for 30 seconds...
145
Sleeping for 30 seconds...
150
Sleeping for 30 seconds...
155
Sleeping for 30 seconds...
160
Sleeping for 30 seconds...
165
Sleeping for 30 seconds...
170
Sleeping for 30 seconds...
175
Sleeping for 30 seconds...
180
Sleeping for 30 seconds...
185
Sleeping for 30 seconds...
190
Sleeping for 30 seconds...
195
Sleeping for 30 seconds...
200
Sleeping for 30 seconds...
205
Sleeping for 30 seconds...
210
Sleeping for 30 seconds...
215
Sleeping for 30 seconds...
220
Sleeping for 30 seconds...
225
Sleeping for 30 seconds...
230
Sleeping for 30 seconds...
235
Sleeping for 30 seconds...
240
Sleeping for 30 seconds...
245
Sleeping for 30 seconds...
250
Sleeping for 30 seconds...
255
Sleeping for 30 seconds...
260
Sleeping for 30 seconds...
265
Sleeping for 30 seconds...
270
Sleeping for 30 seconds...
275
Sleeping for 30 seconds...
280
Sleeping for 30 seconds...
285
Sleeping for 30 seconds...
290
Sleeping for 30 seconds...
295
Sleeping for 30 seconds...
300
Sleeping for 30 seconds...
305
Sleeping for 30 seconds...
310
Sleeping for 30 seconds...
315
Sleeping for 30 seconds...
320
Sleeping for 30 seconds...
325
Sleeping for 30 seconds...
330
Sleeping for 30 seconds...
335
Sleeping for 30 seconds...
340
Sleeping for 30 seconds...
345
Sleeping for 30 seconds...
350
Sleeping for 30 seconds...
355
Sleeping for 30 seconds...
360
Sleeping for 30 seconds...
365
Sleeping for 30 seconds...
370
Sleeping for 30 seconds...
375

In [ ]:
dfmehmeh2["sentiment"] = mehmehlist5

C:\Users\Rald999\AppData\Local\Temp\ipykernel_17580\1814716899.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfmehmeh2["sentiment"] = mehmehlist5

In [ ]:
dfmehmeh2["sentiment"]

0      Neutral.\n\nThe text is simply descriptive. It...
1      Positive.\n\n**Reasoning:**\n\nThe phrases "95...
2      The sentiment of the text is **positive**.\n\n...
3                                             Positive\n
4                                             Positive\n
                             ...
808    The sentiment is **neutral**.\n\nHere's why:\n...
809    **Mixed/Neutral**\n\nHere's the breakdown:\n\n...
810    Neutral.\n\nThe text is simply a product name ...
811                                            Neutral\n
812                                            Neutral\n
Name: sentiment, Length: 378, dtype: object

In [ ]:
dfmehmeh2 = dfmehmeh2.reset_index(drop=True)

In [ ]:
dfmehmeh2["sentiment"] =

In [ ]:
dfmehmeh2["sentiment"] = dfmehmeh2["sentiment"].str.contains

0      neutral.\n\nthe text is simply descriptive. it...
1      positive.\n\n**reasoning:**\n\nthe phrases "95...
2      the sentiment of the text is **positive**.\n\n...
3                                             positive\n
4                                             positive\n
                             ...
373    the sentiment is **neutral**.\n\nhere's why:\n...
374    **mixed/neutral**\n\nhere's the breakdown:\n\n...
375    neutral.\n\nthe text is simply a product name ...
376                                            neutral\n
377                                            neutral\n
Name: sentiment, Length: 378, dtype: object

In [ ]:
dfmehmeh2.to_csv("datacleaned3.csv",index=False)

In [ ]:
dfmehmeh2.loc[dfmehmeh2['sentiment'].str.contains("positive"), 'sentiment'] = "positive"
dfmehmeh2.loc[dfmehmeh2['sentiment'].str.contains("neutral"), 'sentiment'] = "neutral"
dfmehmeh2.loc[dfmehmeh2['sentiment'].str.contains("negative"), 'sentiment'] = "negative"

In [ ]:
dfmehmeh2.to_csv("datacleaned4.csv",index=False)

In [ ]:
dfmehmeh2["sentiment"].value_counts()

sentiment
positive    250
neutral     110
negative     18
Name: count, dtype: int64

In [ ]:
df = df.reset_index()

In [ ]:
mehmehlist6 = gemini_usefulness(df["content"])

Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...

Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...
Sleeping for half minute...

In [ ]:
mehmehlist4

['1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '0\n',
 '1\n',
 '1\n',
 '0\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '0\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '0\n',
 '0\n',
 '1\n',
 '0\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '0\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '1\n',
 '0\n',
 '0\n',
 '1\n']

In [ ]:
df4["useful"] = mehmehlist3

In [ ]:
df2["useful"] = mehmehlist2

In [ ]:
tempdf["useful"] =mehmehlist4

In [ ]:
tempdf

,Unnamed: 0,url,content,useful
0,0,https://www.t3.com/reviews/secretlab-titan-evo...,The Secretlab Titan Evo Lite is a brand-new ch...,1\n
1,1,https://gamerant.com/secretlab-titan-evo-lite-...,"As Secretlab explains, the chair features 95% ...",1\n
2,2,https://www.gamespot.com/articles/secretlabs-n...,"Overall, Secretlab's Titan Evo Lite is a fanta...",1\n
3,3,https://www.hardwarezone.com.sg/review-secretl...,"Starting from S$519, Secretlab says this new v...",1\n
4,4,https://secretlab.eu/sv/products/titan-evo-202...,"Customer Reviews . 4.9 Based on 52,709 Reviews...",1\n
...,...,...,...,...
77,77,https://www.tiktok.com/@zachstechturf/video/74...,Gaming Chair Temu Review · Guy behind ... Secr...,1\n
78,78,https://m.youtube.com/watch?v=meDhajzejwM&pp=y...,Comments · What Size Titan Evo 2022 Should You...,1\n
79,79,https://www.tiktok.com/discover/secret-lab-tit...,I have not sit in this chair yet. I'm about to...,0\n
80,80,https://www.youtube.com/watch?v=FEGM3Lh2RKU&pp...,Support the channel and BUY IT HERE: Secretlab...,0\n
81,81,https://secretlab.co/products/titan-xxs,A sleek black gaming chair with gold accents l...,1\n

In [ ]:
tempdf.to_csv("data0.csv")

In [ ]:
df2.to_csv("data2.csv")
df4.to_csv("data4.csv")

In [ ]:
mehmehlist

['1\n', '1\n', '1\n', '1\n', '1\n']

In [ ]:
df4["content"].head(5)

0    The Secretlab Titan Evo Lite is a brand-new ch...
1    As Secretlab explains, the chair features 95% ...
2    In gaming chairs, Secretlab has left a mark as...
3    Starting from S$519, Secretlab says this new v...
4    The Secretlab Titan Evo 2022 is a firm gaming ...
Name: content, dtype: object

In [ ]:
pront(xxxxxxx)

NameError: name 'pront' is not defined

In [ ]:
import re

def clean_text(text):                               # user defined function for cleaning text
    text = text.lower()                             # all lower case
    text = re.sub(r'\[.*?\]', ' ', text)            # remove text within [ ] (' ' instead of '')
    text = re.sub(r'\<.*?\>', ' ', text)            # remove text within < > (' ' instead of '')
    text = re.sub(r'http\S+', ' ', text)            # remove website ref http
    text = re.sub(r'www\S+', ' ', text)             # remove website ref www

    text = text.replace('€', 'euros')               # replace special character with words
    text = text.replace('£', 'gbp')                 # replace special character with words
    text = text.replace('$', 'dollar')              # replace special character with words
    text = text.replace('%', 'percent')             # replace special character with words
    text = text.replace('\n', ' ')                  # remove \n in text that has it

    text = text.replace('\'', '’')                  # standardise apostrophe
    text = text.replace('&#39;', '’')               # standardise apostrophe

    text = text.replace('’d', ' would')             # remove ’ (for would, should? could? had + PP?)
    text = text.replace('’s', ' is')                # remove ’ (for is, John's + N?)
    text = text.replace('’re', ' are')              # remove ’ (for are)
    text = text.replace('’ll', ' will')             # remove ’ (for will)
    text = text.replace('’ve', ' have')             # remove ’ (for have)
    text = text.replace('’m', ' am')                # remove ’ (for am)
    text = text.replace('can’t', 'can not')         # remove ’ (for can't)
    text = text.replace('won’t', 'will not')        # remove ’ (for won't)
    text = text.replace('n’t', ' not')              # remove ’ (for don't, doesn't)

    text = text.replace('’', ' ')                   # remove apostrophe (in general)
    text = text.replace('&quot;', ' ')              # remove quotation sign (in general)

    text = text.replace('cant', 'can not')          # typo 'can't' (note that cant is a proper word)
    text = text.replace('dont', 'do not')           # typo 'don't'

    text = re.sub(r'[^a-zA-Z0-9]', r' ', text)      # only alphanumeric left
    text = text.replace("   ", ' ')                 # remove triple empty space
    text = text.replace("  ", ' ')                  # remove double empty space
    return text

# for i in range(len(comment_list)):
#     print(comment_list[i])                          # pre-clean
#     comment_list[i] = clean_text(comment_list[i])   # overwrite with clean_text function
#     print(comment_list[i])

In [ ]:
df["content"] = df["content"].apply(clean_text)

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rald999\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def remove_stopword(text):
   
   text = " ".join(word for word in text.split() if word not in stopwords)
   return text

In [ ]:
df["content"] = df["content"].apply(remove_stopword)

In [ ]:
mehmehstring = ' '.join(df['content'].tolist())

In [ ]:
mehmehstring

'secretlab titan evo lite brand new chair one biggest names gaming chairs designed offer 95percent premium experience secretlab titan evo 20percent secretlab explains chair features 95percent titan evo features 20percent less cost gamers testing titan evo lite feel like downgrade overall secretlab titan evo lite fantastic gaming chair price point though original titan evo bit versatility lite offers many impactful features starting sdollar519 secretlab says new variant designed offer accessible price point without compromising quality comfort titan evo chairs known titan evo goes lite glance titan evo lite looks identical expensive predecessor customer reviews 4 9 based 52 709 reviews 5 secretlab titan evo titan evo lite chairs sale eligible 30 day free returns exception secretlab automobili lamborghini collection secretlab titan evo house dragon edition lacks standard evo adjustable lumbar support uses upholstery materials last seen 2020 titan line titan evo lite sturdy comfortable chair long gaming sessions secretlab titan evo 2022 firm gaming chair supports back right ways including lumbar support system place right height firmness entry level gaming chair starting gaming indulgence chair delivers comfort support slightly scaled back features affordable price point starting sdollar519 chair bears similarities 2022 secretlab titan evo streamlines best features comfortable gaming experience secretlab titan evo lite black prime 2 0 leatherette gaming chair reclining ergonomic heavy duty computer chair 4d armrests lumbar support black visit secretlab store 4 3 4 3 5 stars 55 ratings secretlab titan evo lite secretlab titan xxs 10 000 5 star ratings multiple editors choice awards wrong find makes secretlab chairs great reviews press real users techradar tweaktown gameranx geek culture trustpilot trustpilot awards reviews secretlab titan evo gaming chairs shop secretlab titan evo lite built performance dna flagship titan evo engineered provide core secretlab experience trusted 3 million users worldwide titan evo lite retains science backed ergonomic design support right places secretlab titan evo lite built performance dna flagship titan evo engineered provide core secretlab experience trusted 3 million users worldwide titan evo lite retains science backed ergonomic design support right places secretlab titan evo lite built performance dna flagship titan evo engineered provide core secretlab experience trusted 3 million users worldwide titan evo lite retains science backed ergonomic design support right places titan evo 2022 secretlab firing cylinders wonderfully comfortable chair long periods working gaming clever new features magnetic head rest put show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners members online positivevibes845 titan evo 2022 r review reviews background titan evo great gaming chair sacrifices comfort nice aesthetics support channel buy reviewing new secretlab titan evo lite softweave gaming chair surprise meet secretlab titan evo gaming chair personalized ergonomics world leading comfort one gaming chair secretlab titan evo series gaming chair customer reviews customer reviews customer reviews secretlab titan evo titan evo lite chairs sale eligible 30 day trial 30 day free returns check secretlab titan evo lite review details secretlab titan evo lite gaming chair starting dollar449 secretlab titan evo lite gaming chair 4 dollar449 00 save 7percent see secretlab titan evo compares high end office chairs unfiltered titan evo review pros cons expert insights titan evo redefined gaming chair comfort three groundbreaking features first integrated height x depth adjustable lumbar provides precise support lower back new secretlab meet secretlab titan evo gaming chair personalized ergonomics world leading comfort one gaming chair secretlab titan evo lite core features less chair add ons ergonomic recliner add new chair accessories explore chairs thank submitting review input much appreciated amazon com secretlab titan evo lite stealth prime 2 0 leatherette gaming chair reclining ergonomic heavy duty computer chair 4d armrests lumbar support black red home kitchen customer reviews price recommended height weight 5 7 6 2 220lbs subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners meet secretlab titan evo gaming chair personalized ergonomics world leading comfort one gaming chair secretlab titan evo series gaming chair customer reviews customer reviews customer reviews secretlab titan evo titan evo lite chairs sale eligible 30 day trial exception meet secretlab titan evo gaming chair personalized ergonomics world leading comfort one gaming chair secretlab titan evo lite core features less chair add ons ergonomic recliner add new chair accessories explore chairs thank submitting review input much appreciated meet secretlab titan evo gaming chair personalized ergonomics world leading comfort one gaming chair secretlab titan evo series gaming chair customer reviews customer reviews customer reviews secretlab titan evo titan evo lite chairs sale eligible 30 day trial exception faux leather r sized titan evo tested sturdy comfortable even slightly easier assemble gaming chairs secretlab continues stand making best secretlab one favorite gaming chair manufacturers due excellent build quality materials company chairs cheap though titan evo editors choice meet secretlab titan evo gaming chair personalized ergonomics world leading comfort one gaming chair secretlab titan evo series gaming chair customer reviews customer reviews customer reviews secretlab titan evo titan evo lite chairs sale eligible 30 day trial exception secretlab finally announced new gaming chair 2024 familiar secretlab titan evo lite wallet friendly version titan evo 2022 would review secretlab titan evo 2022 series extendable five years dollar50 social media post chair new titan evo 2022 series gaming chair refined discover features innovations behind latest gaming chair titan evo 4 way lumbar support magnetic head pillow secretlab titan evo lite core features less ergonomics technology reviews resources aftercare peel protection warranty extension referral program atome financing instalment plans discover features innovations behind latest gaming chair titan evo 4 way lumbar support magnetic head pillow limited time offer secretlab titan evo lite core features less ergonomics technology reviews resources aftercare warranty extension referral program affirm taskrabbit try products sit incredibly easily secretlab titan large spacious gaming chair integrated lumbar support upgrade sitting experience secretlab titan evo lite core features less secretlab titan 2020 gaming chair renowned ample space ergonomic customization highest level secretlab titan evo lite core functions flagship titan evo accessible price ergonomic chair engineered day comfort limited time 30 day free returns comfort deeper personalization exceptional durability research backed design innovations engineered serious performance secretlab titan evo first gaming chair kind elevate game pro grade ergonomics choice world best players professionals worldwide obviously overall level comfort secretlab titan evo lite able provide yet seen seem like reasonable concessions considering asking price hils p secretlab titan evo gamer stol personaliseret ergonomisk og verdensf rende komfort alt n gamer stol secretlab gaming stole er bygget til kunne tilpasses meget og har en lang r kke justeringsmuligheder secretlab titan evo titan evo lite chairs sale eligible 30 day free returns longest time wanted secretlab titan review finally chance honest review secretlab titan evo gaming chair thank secretlab sending us review thoughts 100percent honest tell every brand whose products review always case amazon com secretlab titan evo lite charcoal blue softweave gaming chair reclining ergonomic heavy duty computer chair 4d armrests lumbar support dark grey blue home kitchen secretlab titan evo black gaming chair reclining ergonomic heavy duty computer chair 4d armrests magnetic head pillow lumbar secretlab titan evo lite leatherette softweave fabric dollar459 dollar419 secretlab save dollar40 favorite gaming chair come cheap prices risen consistently since subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners secretlab titan evo lite core features less strongly recommend watch attempting assemble secretlab gaming chair contains vital safety information tips make assembly process smoother users take 20 minutes assemble chair thank submitting gaming chair features secretlab titan evo secretlab us ergonomic recliner add new secretlab skins best seller magnus monitor arms new chair add ons desk add ons secretlab titan xxs shop products gaming chairs computer desks accessories warranty extension secretlab business research backed design innovations engineered serious performance secretlab titan evo first gaming chair kind engineered class 4 hydraulics shorter secretlab titan evo small regular accommodate even people achieve proper ergonomic posture whether game work even pressure distribution sitting secretlab titan evo chair subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners one likes painful price gaming chairs demand titan evo get jail free card work play chair originally posted jul 12 2021 5 00 pm verdict subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners gaming chairs secretlab titan evo secretlab us secretlab skins best seller premium chair sleeves refresh look chair magnus monitor arms new find perfect ergonomic view chair add ons personalize secretlab sitting experience desk add ons achieve unrivaled cable management secretlab physical gift box new gift titan evo chair without heavy lifting ergonomic recliner add new secretlab skins best seller magnus monitor arms new chair add ons desk add ons secretlab titan xxs shop products gaming chairs computer desks accessories warranty extension secretlab business secretlab titan evo series gaming chair refer return policy information secretlab titan evo oracle red bull racing edition chair secretlab titan evo nanogen edition comfortable variant brand flagship gaming chair comfortable would like ron burgundy owned subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners secretlab titan evo lite designed bring award winning titan evo experience many people possible could made much cheaper chair cheaper materials fewer features compromising durability performance overall experience secretlab maker favourite gaming chair secretlab titan evo launching cheaper model shares many characteristics best gaming chair called titan evo lite secretlab titan evo lite leatherette softweave fabric gbp459 gbp429 secretlab uk save gbp30 favorite gaming chair come cheap prices risen consistently since secret lab titan evo review r secretlab skip main content secret lab titan evo review r secretlab secret lab titan evo review secret lab titan evo chair honest review case feel compelled write secret lab titan evo chair bought recently expensive perhaps would bothered given cost secret lab chair worth asking question secret lab titan evo chair worth price titan evo secret lab chair uncomfortable good luck works sitting secret lab chair like sitting concrete secret lab chair titan evo gaming setup titan evo best gaming chair current price dollar609 batman fans themed chair lovers check secretlab titan evo dark knight edition gotham style meets gaming comfort think epic batman vibes top notch ergonomics titan evo total game changer setup anyone wanting buy secretlab chair favor search secretlab chair back pain titan evo 2022 put back surgery many others see issues chairs company rely google reviews becauise would sink secretlab titan evo gaming chair discounted presidents day razer pc adjacent ces lineup includes monitor stand lights chair integrated heating cooling fractal refine secretlab titan evo 2022 series regular secretlab neo hybrid leatherette stealth arrived last week best chair personally comfort quality excellent unboxing finally getting sit work provided basic chair working home got rid would never go back still old chair would return every see opinion changed yet every time would almost relief sit soft cheap office chair compared sl titan personally convinced never issues sitting extended periods softer chairs find generally comfortable even 5 5 years sitting stiff sl titan still find pleasantly surprised sit another chair sink actual soft cushion sit disintegrates buy entirely different chair secretlab chair honest subreddit things secretlab engineer award winning performance gaming chairs work play show awesome setups discuss secretlab titan evo secretlab classics secretlab magnus catch fellow secretlab soon owners anyone view post comment community please note required r gaming community karma make post please comment around posting posts promoting spamming brigading raiding others subs eg pass memes removed result permanent ban trade posts contests hosted subreddit removed curb karma farming due community feedback askreddit style open ended discussion prompts must submitted self posts image versions removed posts comments whether jest malice contain racist sexist homophobic threats toxic content removed regardless popularity relevance post rules anyone view post comment community posting content please enquire mods allowed self promote self promoted content must topic gaming leaks rumors keep posts topic leaks rumours post must related video game leaks rumours piece news related leak rumour posted previously subreddit use active megathread one active posts related removed moderators discretion command used comment section post proven false misleading comment debunks post reddit dive anything open menu open navigation go reddit home r officechairs chip close button r officechairs r officechairs ultimate chair buying guide 2023 finished ultimate chair buying guide 2023 reddit reddit reddit action movies series animated movies series comedy movies series crime mystery thriller movies series documentary movies series drama movies series fantasy movies series horror movies series movie news discussion reality tv romance movies series sci fi movies series superhero movies series tv news discussion communities best reddit topics reddit heart internet open menu open navigation go reddit home website prices look good true scam right website popped ad instagram feed new reddit create account connect world communities top posts reddit rereddit top posts november 28 2023 reddit rereddit top posts november 2023 reddit rereddit top posts 2023 reddit rules privacy policy user agreement reddit inc communities best reddit topics cricket official promoted redirecting r poshmark welcome r gaminglaptops hub gaming laptop enthusiasts discover discussions news reviews advice finding perfect gaming laptop join passionate community stay informed connected latest trends technologies gaming laptop world go furniture real person try anabei couches top posts reddit reddit reddit reddit inc tradestation customizable platform enables experienced traders plan execute cme group futures products seconds password new reddit enter 6 digit code authenticator app enter 6 digit backup code use code authenticator app reddit anonymous username go password reddit anonymous username go password enter email address username send link reset password email link reset password sent email address associated account choose reddit account continue new password rocksteady looking make new singleplayer batman game warner wonder woman game struggling andy chalk published 7 february 25 news bad year warner bros civilization 7 live launch coverage reviews tips latest news tyler wilde last updated 7 february 25 live keep tabs everything civilization 7 first new firaxis grand strategy game nearly decade makes entrance eight months brave new world windows arm state play pc gaming outside x86 arena ian evenden published 6 february 25 woa h qualcomm serious gaming ambitions snapdragon x elite look like half year line woa h reddit dive anything anyone view post comment community reddit reddit reddit action games adventure games esports gaming consoles gear gaming news discussion mobile games games role playing games simulation games sports racing games strategy games tabletop games q stories confessions action movies series animated movies series comedy movies series crime mystery thriller movies series documentary movies series drama movies series fantasy movies series horror movies series movie news discussion reality tv romance movies series sci fi movies series superhero movies series tv news discussion communities best reddit topics reddit inc create post daily set reduced 5 points megathread votes comments living sticky 4 updated daily votes comments anyone view post comment community posting referral links codes posting referral links codes sort allowed content created breaks subreddit rules may removed without warning includes breaking rule 3 referral links codes description video allowed post rip streak look day streak funny points amount lots points similar posts communities best reddit topics reddit inc amd ryzen 9 9950x3d review stunning gaming performance meets top tier productivity 2 select download option click download button ryzen master ensure downloading nvidia new tech reduces vram usage 96percent beta demo aaron klotz published 8 february 25 nvidia upcoming rtx neural texture compression tested rtx 4090 shows impressive 96percent reduction texture memory size compared outgoing texture compression techniques nvidia investigating rtx 5090 rtx 5080 instability issues roshan ashraf shaikh published 8 february 25 stopgap solutions exist wait nvidia official fix zotac selling rtx 50 series gpus directly customers thwart scalpers jowi morales published 8 february 25 zotac usa implements priority access system sell rtx 5080 rtx 5090 gpus directly fans discord server welcome r gaminglaptops hub gaming laptop enthusiasts discover discussions news reviews advice finding perfect gaming laptop join passionate community stay informed connected latest trends technologies gaming laptop world sovol sv06 ace super affordable speedy bedslinger style prusa i3 machines excellent quality speed thanks klipper comes surprising number perks reddit dive anything open menu open navigation go reddit home new reddit create account connect world communities anyone view post comment community top posts reddit reddit reddit rereddit top posts 2018 reddit rules privacy policy user agreement reddit inc action movies series animated movies series comedy movies series crime mystery thriller movies series documentary movies series drama movies series fantasy movies series horror movies series movie news discussion reality tv romance movies series sci fi movies series superhero movies series tv news discussion communities best reddit topics lenovo com welcome r gaminglaptops hub gaming laptop enthusiasts discover discussions ne

In [ ]:
from collections import Counter
from nltk.util import everygrams

print("Finding top words...")

top_length = 3                # top_length > 1 not useful after removing stopwords
num_top = 30

e_grams_counts = Counter(everygrams(mehmehstring.split(), max_len=top_length))
e_grams_most = e_grams_counts.most_common(num_top)
print(e_grams_most)
print("Number of e-grams found:", len(e_grams_most))

Finding top words...
[(('secretlab',), 143), (('titan',), 127), (('evo',), 120), (('titan', 'evo'), 118), (('chair',), 95), (('gaming',), 93), (('series',), 87), (('reddit',), 83), (('secretlab', 'titan'), 78), (('movies',), 77), (('movies', 'series'), 77), (('secretlab', 'titan', 'evo'), 72), (('gaming', 'chair'), 48), (('lite',), 43), (('titan', 'evo', 'lite'), 38), (('evo', 'lite'), 38), (('chairs',), 28), (('reviews',), 28), (('r',), 27), (('new',), 26), (('posts',), 23), (('news',), 23), (('best',), 22), (('open',), 18), (('reddit', 'reddit'), 18), (('features',), 17), (('top',), 17), (('discussion',), 17), (('review',), 16), (('subreddit',), 16)]
Number of e-grams found: 30

: